### ISSUE TITLE
Does not create compiled story files

### ISSUE THREAD

**Issue by shift838** [ByteProject/Puny-BuildTools#5] opened 2023-05-25 18:19 UTC
I have followed the document to set up the build tools on a real linux workstation.  Copied my storyfile (.inf) file over to my project directory.  Edited the required .sh files but when running the .sh file to compile and create the disk images, it creates the disk image but does not compile or copy the story files to the disk image.  When it goes to cleanup it says it cannot find it since it did not create them.  I also have the inform compiler for my linux that was installed via the sudo apt-get install command.

Any clues?

**Comment by ByteProject** [comment] 2023-05-26 07:19
Ok, we'll get this running. A few questions:

Which Linux are you using? Based on sudo apt-get you mentioned it must be Debian or one of its derivates like Ubuntu?

Which .sh file did you try?

Have you copied the BuildTools folder to your home directory and do you have it at path? As well as it's subfolders as mentioned in the documentation?

PunyInform is installed? 

Have you edited the 'puny' file in the BuildTools dir so that it has the correct path to the PunyInform library?

What happens if you go into your project dir and you try to create a Story file with 'puny mystory.inf'?

Have you excluded the Inform compiler from the BuildTools because you have your own version installed? That likely doesn't work because the puny utility wants the compiler from the BuildTools dir (which is newer than the version you get with sudo-apt get and it also is named differently to not getting confused with existing binaries on the host system). It's recommended that you use the compiler that came with the BuildTools or a newer version that you can compile yourself very easy with gcc. The sources are up on David Kinder's GitHub. If you use a newer compiled version using the sources from David's github, place it in the BuildTools folder. The stable Inform compiler version you get with sudo apt-get is too old and misses a few features Puny uses. I'd recommend deinstalling it.

When you try to run the shell script, if you scroll up in your terminal are there any error messages to be seen? For instance that the compiler found an error in the source and does not create a Story file?

I would always recommend that you first try if you get a working story file from your source with 'puny my story.inf' to make sure all is fine before you trigger one of the shell scripts to create a retro disk image.

PS: You can use the test.sh script to quickly check if your game compiles and then fire up Frotz to test it. Not sure if you run this on a real Linux or a WSL2 environment like me but you may want to alter the test.sh so that it launches Frotz installed on your Linux station. For this you can install Frotz via sudo apt-get. This is my Workflow. I change / develop my story file, run test.sh to make sure it compiles and test the changes. Once all is fine and I want to distribute I use the shell scripts.

**Comment by shift838** [comment] 2023-05-26 22:05
I am using Ubuntu after looking closer I found that it was not able to locate the library files for some reason..  I had to create a folder that it was looking for and put them in there.  after re-reading the install documentation, I see I missed changing it in the puny wrapper program.  

It was looking for the library files in my home directory for:
~/Projects/8bit/Z-Machine/lib/lib

I got it working.  No I need to find a complete program reference to PunyInform.  I have not found a reference guide to every command anywhere, not even in the punyInform manual.

so far I have been successful compiling my first IIF adventure for the TI-99/4A and Atari ST.  I tried for the Amiga but just got a blank image.  gotta look into that some more.

**Comment by shift838** [comment] 2023-05-27 06:19
When compiling for the Amiga, i just get a blank disk image.  Below is what is shown on my Ubuntu when compiling for Amiga.

Inform 6.36 (in development)
No such memory setting as "ZCODE_LESS_DICT_DATA"
In:  7 source code files              6397 syntactic lines
  9575 textual lines                258336 characters (ISO 8859-1 Latin1)
Allocated:
   983 symbols                      717166 bytes of memory
Out:   Version 3 "Standard" story file 1.230523 (27.5K long):
     4 classes                          17 objects
    94 global vars (maximum 233)      1354 variable/array space
    61 verbs                           197 dictionary entries
   125 grammar lines (version 2)       231 grammar tokens (unlimited)
    69 actions                          30 attributes (maximum 32)
    26 common props (maximum 29)         9 individual props (unlimited)
 19684 bytes of Z-code                 360 unused bytes stripped out (1.8%)
  7842 characters used in text        4930 bytes compressed (rate 0.628)
    64 abbreviations (maximum 64)      230 routines (unlimited)
  4635 instructions of Z-code         2938 sequence points
  5696 bytes readable memory used (maximum 65536)
 27926 bytes used in Z-machine      103146 bytes free in Z-machine
Completed in 0.000 seconds

**Comment by ByteProject** [comment] 2023-05-27 09:14
This definitely has something to do with your setup. I am suspecting that XDFTOOL is not at your path, which is the tool that is used to copy files to Amiga disk images. It's part of the amitools package that came with the BuildTools (located in the FictionTools folder). amitools/XDFTOOL needs Python, but that should be installed by default on your Ubuntu so that shouldn't be the issue. 

What I can highly recommend is that if a script fails for you, open it, investigate the steps in the script and try to do it by hand first step by step so that you see where it fails. In this case it definitely has to do with XDFTOOL. So either Python is not found on your system or like I said XDFTOOL is not at path.

You can quickly check this by typing 'xdftool' in your terminal. It should greet you like this: 

<img width="865" alt="xdftool" src="https://github.com/ByteProject/Puddle-BuildTools/assets/153544/364f86c1-d7e1-44ea-bfea-fb7fd909887c">

Check the .bashrc file you have in your home directory and make sure you've added all the paths that were mentioned in the installation instructions of the documentation: 

<img width="544" alt="Bildschirmfoto 2023-05-27 um 09 53 08" src="https://github.com/ByteProject/Puddle-BuildTools/assets/153544/698854b0-6407-4def-ae5d-d34cedcbc7ab">

It should work then. I am closing this issue now as each script has been tested and works fine on Ubuntu based systems, so this is likely a user config issue, which I am sure we can resolve. What I would suggest is that you join our (pretty active) PunyInform Discord server, where fellow adventure authors are happy to assist with all kinds of topics from game design to code: [https://discord.gg/kcMff45NfE](url)

Regarding the PunyInform documentation. There is unfortunately no such thing as a complete documentation. The problem is that PunyInform is based, as the name suggests on the Inform language, which has its very own documentation. So before you can start with PunyInform, you need to understand Inform itself. 

But here are the most valuable resources: 

The Inform Designer's Manual 4 (DM4) by Graham Nelson: [PDF version](https://www.inform-fiction.org/manual/DM4.pdf)

The PunyInform Manual: [Online version](https://github.com/johanberntsson/PunyInform/wiki/manual)

Hope this helps! See you on the Discord :)

**Closed as completed by ByteProject** 2023-05-27 09:14 UTC

**Comment by shift838** [comment] 2023-05-28 03:31
perfect...
